version: '3.8'
services:
  parakeet-api-docker:
    container_name: parakeet-api-docker
    image: ghcr.io/fqscfqj/parakeet-api-docker:full
    ports:
      - "5092:5092"
    volumes:
      - ./models:/app/models:ro
      - ./temp_uploads:/app/temp_uploads
    environment:
      # 简版环境变量（更多可选项见 README.md）
      - ENABLE_LAZY_LOAD=true
      - DECODING_STRATEGY=greedy
      - API_KEY=
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]