name: 🐳 Docker Build & Push

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
    paths:
      - 'Dockerfile*'
      - 'app.py'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Dockerfile*'
      - 'app.py'
      - 'requirements.txt'
      - '.github/workflows/docker-build.yml'
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      push_image:
        description: '是否推送镜像到registry'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      build_slim:
        description: '是否构建slim版本'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fqscfqj/parakeet-api-docker

jobs:
  build:
    name: 🔨 Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: standard
            dockerfile: Dockerfile
            suffix: ""
            platforms: "linux/amd64"
          - variant: slim
            dockerfile: Dockerfile.slim
            suffix: "-slim"
            platforms: "linux/amd64,linux/arm64"
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: 🔐 Log in to Container Registry
        if: github.event_name != 'pull_request' && (github.event.inputs.push_image != 'false')
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏷️ Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            suffix=${{ matrix.suffix }},onlatest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=commit-{{sha}}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=Parakeet ASR API${{ matrix.suffix && format(' ({0})', matrix.variant) || '' }}
            org.opencontainers.image.description=NeMo Parakeet ASR API Docker image${{ matrix.suffix && format(' - {0} version', matrix.variant) || '' }}
            org.opencontainers.image.vendor=fqscfqj

      - name: 🚫 Skip slim build if disabled
        if: matrix.variant == 'slim' && github.event.inputs.build_slim == 'false'
        run: |
          echo "跳过slim版本构建"
          exit 0

      - name: 🔨 Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' && github.event.inputs.push_image != 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: 📋 Output image digest
        if: github.event_name != 'pull_request' && (github.event.inputs.push_image != 'false')
        run: |
          echo "## 🐳 Docker镜像构建完成" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**镜像版本:** ${{ matrix.variant }}" >> $GITHUB_STEP_SUMMARY
          echo "**Dockerfile:** ${{ matrix.dockerfile }}" >> $GITHUB_STEP_SUMMARY
          echo "**支持平台:** ${{ matrix.platforms }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**标签信息:**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  security-scan:
    name: 🔍 Security Scan
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    
    permissions:
      contents: read
      packages: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        variant: [standard, slim]
    
    steps:
      - name: 🔐 Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}${{ matrix.variant == 'slim' && '-slim' || '' }}
          format: 'sarif'
          output: 'trivy-results-${{ matrix.variant }}.sarif'
          severity: 'CRITICAL,HIGH'

      - name: 📤 Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-${{ matrix.variant }}.sarif'
          category: 'trivy-${{ matrix.variant }}'

  update-description:
    name: 📝 Update Package Description
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      packages: write
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔐 Log in to Container Registry  
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📝 Update package description
        run: |
          # 更新标准版描述
          echo "更新标准版镜像描述..."
          docker buildx imagetools create \
            --annotation "index:org.opencontainers.image.description=🎙️ NeMo Parakeet ASR API - 高性能语音识别服务，支持长音频分片处理、GPU加速和多种输出格式。Standard version with full features." \
            --annotation "index:org.opencontainers.image.documentation=https://github.com/fqscfqj/parakeet-api-docker" \
            --annotation "index:org.opencontainers.image.source=https://github.com/fqscfqj/parakeet-api-docker" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          # 更新slim版描述
          echo "更新slim版镜像描述..."
          docker buildx imagetools create \
            --annotation "index:org.opencontainers.image.description=🎙️ NeMo Parakeet ASR API - 高性能语音识别服务，支持长音频分片处理、GPU加速和多种输出格式。Slim version with optimized size." \
            --annotation "index:org.opencontainers.image.documentation=https://github.com/fqscfqj/parakeet-api-docker" \
            --annotation "index:org.opencontainers.image.source=https://github.com/fqscfqj/parakeet-api-docker" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-slim

  test-images:
    name: 🧪 Test Images
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    
    strategy:
      fail-fast: false
      matrix:
        variant: [standard, slim]
    
    steps:
      - name: 🔐 Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Test image startup
        run: |
          # 设置镜像名称
          if [ "${{ matrix.variant }}" = "slim" ]; then
            IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-slim"
          else
            IMAGE_TAG="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          fi
          
          echo "测试镜像: $IMAGE_TAG"
          
          # 创建临时目录
          mkdir -p ./test_models ./test_uploads
          
          # 启动容器进行基础测试
          docker run -d \
            --name test-container-${{ matrix.variant }} \
            -p 5092:5092 \
            -v ./test_models:/app/models:ro \
            -v ./test_uploads:/app/temp_uploads \
            -e ENABLE_LAZY_LOAD=true \
            -e IDLE_TIMEOUT_MINUTES=1 \
            $IMAGE_TAG
          
          # 等待容器启动
          echo "等待容器启动..."
          sleep 30
          
          # 检查容器状态
          if ! docker ps | grep test-container-${{ matrix.variant }}; then
            echo "❌ 容器启动失败"
            docker logs test-container-${{ matrix.variant }}
            exit 1
          fi
          
          # 测试健康检查端点
          echo "测试健康检查端点..."
          if curl -f http://localhost:5092/health/simple; then
            echo "✅ 健康检查端点响应正常"
          else
            echo "❌ 健康检查端点响应异常"
            docker logs test-container-${{ matrix.variant }}
            exit 1
          fi
          
          # 清理
          docker stop test-container-${{ matrix.variant }} || true
          docker rm test-container-${{ matrix.variant }} || true
          
          echo "✅ ${{ matrix.variant }} 版本镜像测试通过"

  notify-completion:
    name: 🎉 Notify Completion
    runs-on: ubuntu-latest
    needs: [build, security-scan, test-images]
    if: always() && github.event_name != 'pull_request'
    
    steps:
      - name: 📊 Generate summary
        run: |
          echo "## 🐳 Docker镜像构建完成" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**构建结果:**" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.build.result }}" = "success" ]; then
            echo "- ✅ 镜像构建: 成功" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ 镜像构建: 失败" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.security-scan.result }}" = "success" ]; then
            echo "- ✅ 安全扫描: 通过" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.security-scan.result }}" = "skipped" ]; then
            echo "- ⏭️ 安全扫描: 跳过" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ 安全扫描: 失败" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-images.result }}" = "success" ]; then
            echo "- ✅ 镜像测试: 通过" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.test-images.result }}" = "skipped" ]; then
            echo "- ⏭️ 镜像测试: 跳过" >> $GITHUB_STEP_SUMMARY
          else
            echo "- ❌ 镜像测试: 失败" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**可用镜像:**" >> $GITHUB_STEP_SUMMARY
          echo "- 标准版: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "- 轻量版: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-slim\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**使用方法:**" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "docker run -p 5092:5092 -v ./models:/app/models:ro ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
